---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: demo
  annotations:
    backstage.io/kubernetes-id: demo
    backstage.io/kubernetes-label-selector: demo
spec:
  type: website
  lifecycle: experimental
  owner: guests
