---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-cluster-view-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-view
subjects:
  - kind: ServiceAccount
    name: default # replace with the name of the SA that your Backstage runs as
    namespace: flux
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sync-flux-resources
rules:
  - apiGroups: ['source.toolkit.fluxcd.io']
    resources:
      [
        'buckets',
        'helmcharts',
        'gitrepositories',
        'helmrepositories',
        'ocirepositories',
      ]
    verbs: ['patch']
  - apiGroups: ['kustomize.toolkit.fluxcd.io']
    resources: ['kustomizations']
    verbs: ['patch']
  - apiGroups: ['helm.toolkit.fluxcd.io']
    resources: ['helmreleases']
    verbs: ['patch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-sync-flux-resources-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sync-flux-resources
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default